/* Generated By:JJTree: Do not edit this line. ASTAnnExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package org.jacop.fz;

public class ASTAnnExpr extends SimpleNode {
  // My additions
  String identifier = "";
  boolean ident_present;

  public ASTAnnExpr(int id) {
    super(id);
  }

  public ASTAnnExpr(Parser p, int id) {
    super(p, id);
  }

  String getIdent() {
    return identifier;
  }

  void setIdent(String ID) {
    ident_present = true;
    identifier = ID;
  }

  boolean idPresent() {
    return ident_present;
  }

  @Override
  public String toString() {
    if (ident_present) {
      return super.toString() + "(ident): " + identifier;
    } else {
      return super.toString();
    }
  }
}
/* JavaCC - OriginalChecksum=630861ca1db540584d08dcc361f5d889 (do not edit this line) */
