/* Generated By:JJTree: Do not edit this line. ASTScalarFlatExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public class ASTScalarFlatExpr extends SimpleNode {
  // My part
  // type = 0-int; 1=bool; 2-ident 3=array acces; 4=string; 5=float;
  int type = -1;
  int intValue; // keeps int & boolean 0/1 value
  double doubleValue; // keeps int & boolean 0/1 value
  String ident;
  String st;

  public ASTScalarFlatExpr(int id) {
    super(id);
  }

  public ASTScalarFlatExpr(Parser p, int id) {
    super(p, id);
  }

  public int getType() {
    return type;
  }

  public void setType(int t) {
    type = t;
  }

  public int getInt() {
    return intValue;
  }

  public void setInt(int i) {
    //   	if (i <= JaCoP.core.Constants.MaxInt && i >= JaCoP.core.Constants.MinInt)
    intValue = i;
    //   	else {
    //   	    System.err.println("Error: Too large or too small integer " + i +
    //   			       "; execution aborted");
    //  	    System.exit(0);
    //   	}
  }

  public double getFloat() {
    return doubleValue;
  }

  public void setFloat(double d) {
    doubleValue = d;
  }

  public String getIdent() {
    return ident;
  }

  public void setIdent(String i) {
    ident = i;
  }

  public String getString() {
    return st;
  }

  public void setString(String i) {
    st = i;
  }

  public String toString() {
    String val = "";

    if (type != -1) {
      val =
          switch (type) {
            case 0 -> "(int): " + intValue;
            case 1 -> "(bool): " + intValue;
            case 2 -> "(ident): " + ident;
            case 3 -> "(array access): " + ident + "[" + intValue + "]";
            case 4 -> "(string): " + st;
            case 5 -> "(float): " + doubleValue;
            default ->
                throw new RuntimeException("Internal parsing error; " + getClass().getName());
          };
    }

    return super.toString() + val;
  }
}
/* JavaCC - OriginalChecksum=49c196b8bba1246a7a05b82a5206f622 (do not edit this line) */
