/* Generated By:JJTree: Do not edit this line. ASTSolveExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package org.jacop.fz;

public class ASTSolveExpr extends SimpleNode {
  int type = -1; // 0 - ident, 1 - array access
  int index; // keeps index
  String ident;

  public ASTSolveExpr(int id) {
    super(id);
  }

  public ASTSolveExpr(Parser p, int id) {
    super(p, id);
  }

  public int getType() {
    return type;
  }

  public void setType(int t) {
    type = t;
  }

  public int getIndex() {
    return index;
  }

  public void setIndex(int i) {
    index = i;
  }

  public String getIdent() {
    return ident;
  }

  public void setIdent(String i) {
    ident = i;
  }

  public String toString() {
    String val = "";

    if (type != -1) {
      val =
          switch (type) {
            case 0 -> "(ident): " + ident;
            case 1 -> "(array access): " + ident + "[" + index + "]";
            default ->
                throw new RuntimeException("Internal parsing error; " + getClass().getName());
          };
    }

    return super.toString() + val;
  }
}
/* JavaCC - OriginalChecksum=5931bb897b8f90fb6543ec7905a67886 (do not edit this line) */
