/* Generated By:JJTree: Do not edit this line. ASTVarDeclItem.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package org.jacop.fz;

public class ASTVarDeclItem extends SimpleNode {
  // My additions
  String identifier;
  int kind; // 0=var, 1=non-var; 2=array-var, 3=array-non-var
  int index1, index2; // array indexs: low & high

  public ASTVarDeclItem(int id) {
    super(id);
  }

  public ASTVarDeclItem(Parser p, int id) {
    super(p, id);
  }

  void setId(String ID) {
    identifier = ID;
  }

  String getIdent() {
    return identifier;
  }

  void setIndexes(int i1, int i2) {
    index1 = i1;
    index2 = i2;
  }

  int getLowIndex() {
    return index1;
  }

  int getHighIndex() {
    return index2;
  }

  int getKind() {
    return kind;
  }

  void setKind(int t) {
    kind = t;
  }

  @Override
  public String toString() {
    String limits = "";
    if (kind > 1) {
      limits = "[" + index1 + ".." + index2 + "]";
    }
    String kindS =
        switch (kind) {
          case 0 -> "(var): ";
          case 1 -> "(non-var): ";
          case 2 -> "(array-var): ";
          case 3 -> "(array-non-var): ";
          default ->
              throw new IllegalStateException("Internal parsing error; " + getClass().getName());
        };
    return super.toString() + kindS + identifier + limits;
  }
}
/* JavaCC - OriginalChecksum=0cd4d854fd034047f62c804d8aeaa8e0 (do not edit this line) */
