/* Generated By:JJTree: Do not edit this line. SimpleNode.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,
 * NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */

package org.jacop.fz;

import lombok.extern.slf4j.Slf4j;

/** Simple AST node for flatzinc parser. */
@Slf4j
public class SimpleNode implements Node {

  protected final int id;
  protected Node parent;
  protected Node[] children;
  protected Object value;
  protected Parser parser;

  /**
   * Constructs a simple node with the specified id.
   *
   * @param i the node id
   */
  public SimpleNode(int i) {
    id = i;
  }

  /**
   * Constructs a simple node with the specified parser and id.
   *
   * @param p the parser
   * @param i the node id
   */
  public SimpleNode(Parser p, int i) {
    this(i);
    parser = p;
  }

  /** {@inheritDoc} */
  public void jjtOpen() {
    // Optional lifecycle hook; no action needed for this node type.
  }

  /** {@inheritDoc} */
  public void jjtClose() {
    // Optional lifecycle hook; no action needed for this node type.
  }

  /** {@inheritDoc} */
  public void jjtSetParent(Node n) {
    parent = n;
  }

  /** {@inheritDoc} */
  public Node jjtGetParent() {
    return parent;
  }

  /** {@inheritDoc} */
  public void jjtAddChild(Node n, int i) {
    if (children == null) {
      children = new Node[i + 1];
    } else if (i >= children.length) {
      Node[] c = new Node[i + 1];
      System.arraycopy(children, 0, c, 0, children.length);
      children = c;
    }
    children[i] = n;
  }

  /** {@inheritDoc} */
  public Node jjtGetChild(int i) {
    return children[i];
  }

  /** {@inheritDoc} */
  public int jjtGetNumChildren() {
    return children == null ? 0 : children.length;
  }

  /** {@inheritDoc} */
  public void jjtSetValue(Object value) {
    this.value = value;
  }

  /** {@inheritDoc} */
  public Object jjtGetValue() {
    return value;
  }

  /* You can override these two methods in subclasses of SimpleNode to
  customize the way the node appears when the tree is dumped.  If
  your output uses more than one line you should override
  toString(String), otherwise overriding toString() is probably all
  you need to do. */

  /** {@inheritDoc} */
  @Override
  public String toString() {
    return ParserTreeConstants.jjtNodeName[id];
  }

  /**
   * Returns string representation of the node with prefix.
   *
   * @param prefix the prefix to prepend
   * @return the string representation
   */
  public String toString(String prefix) {
    return prefix + this;
  }

  /* Override this method if you want to customize how the node dumps
  out its children. */

  /**
   * Dumps the node tree to output with indentation.
   *
   * @param prefix the indentation prefix
   */
  public void dump(String prefix) {
    log.info(toString(prefix));
    if (children != null) {
      for (Node child : children) {
        SimpleNode n = (SimpleNode) child;
        if (n != null) {
          n.dump(prefix + " ");
        }
      }
    }
  }

  /**
   * Returns the node id.
   *
   * @return the node id
   */
  public int getId() {
    return id;
  }

  /** Removes all child nodes. */
  void removeChildren() {
    children = null;
  }
}

/* JavaCC - OriginalChecksum=437df12e360880d1ad7d1ba139165523 (do not edit this line) */
