/* Generated By:JJTree: Do not edit this line. ASTAnnExpr.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTAnnExpr extends SimpleNode {
  public ASTAnnExpr(int id) {
    super(id);
  }

  public ASTAnnExpr(Parser p, int id) {
    super(p, id);
  }

    // My additions
    String id="";
    boolean ident_present = false;

    void setIdent(String ID) {
	ident_present = true;
	id = ID;
    }
    String getIdent() {
	return id;
    }

    boolean idPresent() {
	return ident_present;
    }

    public String toString() {
	if (ident_present)
	    return super.toString() + "(ident): " + id;
	else
	    return super.toString();
    }
}
/* JavaCC - OriginalChecksum=630861ca1db540584d08dcc361f5d889 (do not edit this line) */
