/* Generated By:JJTree: Do not edit this line. ASTIntLiterals.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

import java.util.ArrayList;

public
class ASTIntLiterals extends SimpleNode {
  public ASTIntLiterals(int id) {
    super(id);
  }

  public ASTIntLiterals(Parser p, int id) {
    super(p, id);
  }

    // My additions
    ArrayList<Integer> list = new ArrayList<Integer>();
    public void setList(ArrayList<Integer> l) {
	list = l;
    }
    public ArrayList<Integer> getList() {
	return list;
    }

    public String toString() {
	return super.toString() + ": " + list;
    }
}
/* JavaCC - OriginalChecksum=ffe02839639c253f81ec8532a85651dd (do not edit this line) */
