/* Generated By:JJTree: Do not edit this line. ASTSetLiteral.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package org.jacop.fz;

public
class ASTSetLiteral extends SimpleNode {
  public ASTSetLiteral(int id) {
    super(id);
  }

  public ASTSetLiteral(Parser p, int id) {
    super(p, id);
  }

    // My additions
    // 0 - interval, 1 - list
    int type;
    public void setType(int t) {
	type = t;
    }
    public int getType() {
	return type;
    }

    public String toString() {
	String tt ="";
	tt = (type == 0)?"interval":"list";
	return super.toString() + "(" + tt + ")";
    }
}
/* JavaCC - OriginalChecksum=eac36c59f17604f0b8011fa86cdb66d3 (do not edit this line) */
